version: "3.9"


# Common context for all services
x-common-dev: &common-jumiamicroservices
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/jumiamicroservices


services:
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: 
    container_name: mysql
    ports:
      - 33066:3306
    volumes:
      mysql_data:/var/lib/mysql




 ServiceA_Jumia:
   <<: *common-jumiamicroservices
   command: go run ./ServiceA_Jumia
   environment:
      APP_PORT: 60001
   ports:
     - 60005:60001
   restart: on-failure

   links:
     - mysql


 ServiceB_Jumia:
   <<: *common-jumiamicroservices
   command: go run ./ServiceB_Jumia/server.go
   environment:
     SERVICE_A: ServiceA_Jumia:60001
     GRAPH_API_PORT: 80
     MYSQL_DB: 
   ports: 
   - 80:80
   links:
     - ServiceA_Jumia
     - mysql

volumes:
  mysql_data
