// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: protos/JumiaServiceA.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCodes int32

const (
	CountryCodes_KENYA    CountryCodes = 0
	CountryCodes_UGANDA   CountryCodes = 1
	CountryCodes_TANZANIA CountryCodes = 2
	CountryCodes_BURUNDI  CountryCodes = 3
	CountryCodes_GHANA    CountryCodes = 4
	CountryCodes_NIGERIA  CountryCodes = 5
	CountryCodes_EGYPT    CountryCodes = 6
)

// Enum value maps for CountryCodes.
var (
	CountryCodes_name = map[int32]string{
		0: "KENYA",
		1: "UGANDA",
		2: "TANZANIA",
		3: "BURUNDI",
		4: "GHANA",
		5: "NIGERIA",
		6: "EGYPT",
	}
	CountryCodes_value = map[string]int32{
		"KENYA":    0,
		"UGANDA":   1,
		"TANZANIA": 2,
		"BURUNDI":  3,
		"GHANA":    4,
		"NIGERIA":  5,
		"EGYPT":    6,
	}
)

func (x CountryCodes) Enum() *CountryCodes {
	p := new(CountryCodes)
	*p = x
	return p
}

func (x CountryCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountryCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_JumiaServiceA_proto_enumTypes[0].Descriptor()
}

func (CountryCodes) Type() protoreflect.EnumType {
	return &file_protos_JumiaServiceA_proto_enumTypes[0]
}

func (x CountryCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountryCodes.Descriptor instead.
func (CountryCodes) EnumDescriptor() ([]byte, []int) {
	return file_protos_JumiaServiceA_proto_rawDescGZIP(), []int{0}
}

type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_JumiaServiceA_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_JumiaServiceA_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_protos_JumiaServiceA_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CustomerPurchaseDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email        string  `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ParcelWeight float64 `protobuf:"fixed64,2,opt,name=parcel_weight,json=parcelWeight,proto3" json:"parcel_weight,omitempty"`
	PhoneNumber  string  `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CountryCode  int64   `protobuf:"varint,4,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
}

func (x *CustomerPurchaseDetails) Reset() {
	*x = CustomerPurchaseDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_JumiaServiceA_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerPurchaseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerPurchaseDetails) ProtoMessage() {}

func (x *CustomerPurchaseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_protos_JumiaServiceA_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerPurchaseDetails.ProtoReflect.Descriptor instead.
func (*CustomerPurchaseDetails) Descriptor() ([]byte, []int) {
	return file_protos_JumiaServiceA_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerPurchaseDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerPurchaseDetails) GetParcelWeight() float64 {
	if x != nil {
		return x.ParcelWeight
	}
	return 0
}

func (x *CustomerPurchaseDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CustomerPurchaseDetails) GetCountryCode() int64 {
	if x != nil {
		return x.CountryCode
	}
	return 0
}

type DataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PurchaseDetails []*CustomerPurchaseDetails `protobuf:"bytes,1,rep,name=PurchaseDetails,proto3" json:"PurchaseDetails,omitempty"`
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_JumiaServiceA_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_JumiaServiceA_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_protos_JumiaServiceA_proto_rawDescGZIP(), []int{2}
}

func (x *DataResponse) GetPurchaseDetails() []*CustomerPurchaseDetails {
	if x != nil {
		return x.PurchaseDetails
	}
	return nil
}

var File_protos_JumiaServiceA_proto protoreflect.FileDescriptor

var file_protos_JumiaServiceA_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x4a, 0x75, 0x6d, 0x69, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x99, 0x01, 0x0a, 0x17, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x52, 0x0a,
	0x0c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a,
	0x0f, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x0f, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x2a, 0x63, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x09, 0x0a, 0x05, 0x4b, 0x45, 0x4e, 0x59, 0x41, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x47, 0x41, 0x4e, 0x44, 0x41, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x41, 0x4e, 0x5a,
	0x41, 0x4e, 0x49, 0x41, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x55, 0x52, 0x55, 0x4e, 0x44,
	0x49, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x48, 0x41, 0x4e, 0x41, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x4e, 0x49, 0x47, 0x45, 0x52, 0x49, 0x41, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x47, 0x59, 0x50, 0x54, 0x10, 0x06, 0x32, 0x35, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x73, 0x76, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_JumiaServiceA_proto_rawDescOnce sync.Once
	file_protos_JumiaServiceA_proto_rawDescData = file_protos_JumiaServiceA_proto_rawDesc
)

func file_protos_JumiaServiceA_proto_rawDescGZIP() []byte {
	file_protos_JumiaServiceA_proto_rawDescOnce.Do(func() {
		file_protos_JumiaServiceA_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_JumiaServiceA_proto_rawDescData)
	})
	return file_protos_JumiaServiceA_proto_rawDescData
}

var file_protos_JumiaServiceA_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_JumiaServiceA_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_JumiaServiceA_proto_goTypes = []interface{}{
	(CountryCodes)(0),               // 0: CountryCodes
	(*DataRequest)(nil),             // 1: DataRequest
	(*CustomerPurchaseDetails)(nil), // 2: CustomerPurchaseDetails
	(*DataResponse)(nil),            // 3: DataResponse
}
var file_protos_JumiaServiceA_proto_depIdxs = []int32{
	2, // 0: DataResponse.PurchaseDetails:type_name -> CustomerPurchaseDetails
	1, // 1: serviceA.GetCsvData:input_type -> DataRequest
	3, // 2: serviceA.GetCsvData:output_type -> DataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_JumiaServiceA_proto_init() }
func file_protos_JumiaServiceA_proto_init() {
	if File_protos_JumiaServiceA_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_JumiaServiceA_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_JumiaServiceA_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerPurchaseDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_JumiaServiceA_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_JumiaServiceA_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_JumiaServiceA_proto_goTypes,
		DependencyIndexes: file_protos_JumiaServiceA_proto_depIdxs,
		EnumInfos:         file_protos_JumiaServiceA_proto_enumTypes,
		MessageInfos:      file_protos_JumiaServiceA_proto_msgTypes,
	}.Build()
	File_protos_JumiaServiceA_proto = out.File
	file_protos_JumiaServiceA_proto_rawDesc = nil
	file_protos_JumiaServiceA_proto_goTypes = nil
	file_protos_JumiaServiceA_proto_depIdxs = nil
}
