CREATE TABLE IF NOT EXISTS Orders (
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  Parcelweight FLOAT NOT NULL,
  Country      VARCHAR (255) NOT NULL,
  Email        VARCHAR (255) NOT NULL,
  Phone        VARCHAR (255) NOT NULL,
  PRIMARY KEY (ID)
)
