// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewOrder struct {
	Parcelweight float64 `json:"parcelweight"`
	Country      string  `json:"country"`
	Email        string  `json:"email"`
	Phone        string  `json:"phone"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Order struct {
	ID           string  `json:"id"`
	Parcelweight float64 `json:"parcelweight"`
	Country      string  `json:"country"`
	Email        string  `json:"email"`
	Phone        string  `json:"phone"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
